server:
  port: 8081

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: empresa-service
          uri: http://localhost:8082
          predicates:
            - Path=/a/**
          filters:
            - StripPrefix=1

        - id: coordinador_service
          uri: http://localhost:8083
          predicates:
            - Path=/b/**
          filters:
            - StripPrefix=1

        - id: estudiante-service
          uri: http://localhost:8084
          predicates:
            - Path=/c/**
          filters:
            - StripPrefix=1

        - id: proyecto-service
          uri: http://localhost:8085
          predicates:
            - Path=/d/**
          filters:
            - StripPrefix=1

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/sistema
          jwk-set-uri: http://localhost:8080/realms/sistema/protocol/openid-connect/certs
      user-name-attribute: preferred_username
      jwt:
        authorities-claim-name: realm_access.roles
       

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
